### ISSUE TITLE
[BUG] Crash when trying to add host manually

### ISSUE THREAD

**Issue by Username-ghb** [TrueZhuangJia/moonlight-ios#29] opened 2024-11-09 11:22 UTC
BUG:
Alright, so when using this application, i am encountering an issue that when i try to add host manually it just crashes and we are back to the home screen, making it unusable for me as i am trying to add my PC (Sunshine + Moonlight + Tailscale) Setup. 

**Steps to reproduce**
Default app setup freshly installed
Press "Add Host Manually"
Fill in any IP, doesn't matter correct or wrong IP
Press "OK" and it will immediately crash

Supposedly it will just q
(still happens anyways without the tailscale)

**Other Moonlight clients**
- When using the original moonlight client, this issue does not happen
- This issue also happens when i use testflight version of Moonlight ZWM

**Device details (please complete the following information)**
 - iPad OS 18.1
 - Ipad Pro 2024 11inch

**Server PC details**
 - Windows 11 HE

**Additional context**
If i remember correctly it works perfectly when i was using iPadOS 18.0, however i have no idea if 18.1 is a contributing factor because i only tested it today where i have just done a **iCloud Backup Restore (I did a full factory reset on my ipad)**

The app still works if i just use the automatically detected host's from local networks

**Comment by TrueZhuangJia** [comment] 2024-11-09 15:33
known issue. reported by many users. happens in some specific case, especially public IPs or remote NAT IPs
however i'm unable to reproduce. 
If you got a public IP available i'd like to test

**Comment by TrueZhuangJia** [comment] 2024-11-09 15:33
probably related with something i changed to ensure Wake on LAN is working properly

**Comment by Username-ghb** [comment] 2024-11-09 15:49
How recent was the change?
Doesn't explain why I was literally able to use it perfectly last month/week

**Comment by TrueZhuangJia** [comment] 2024-11-09 15:58
this commit:
https://github.com/moonlight-stream/moonlight-ios/commit/bf1a30505ff047091f2d9ff18341669f9d2b40c7
Aug 3

it's also related with network condition.  that's why most people including myself don't meet with issue

**Comment by Username-ghb** [comment] 2024-11-09 16:43
No idea if this make sense, but i have been testing on trying to get this pop up (well i enter wrong IPs anyways because faster way of testing but it is able to update hosts if correct IP entered i tried)
<img width="263" alt="54E435A9-7C29-4DD0-A93C-E9DC7784A236" src="https://github.com/user-attachments/assets/9aeaead4-2981-47ca-ad11-ab70c72ec30b">

The above pop up only appears sometimes when i use DSL, High Latency DNS and 802.11ac. The connection also must be a 2.4Ghz frequency and since it's not a 100% so there's some randomness going on too
When using tailscale/5Ghz there's 0% of that pop up showing up, i have no idea if this even helps but its definitely something i guess? 

Developer Mode is enabled to access this menu
<img width="1210" alt="D17DE138-73DC-444C-AEDF-5B0E0D9C4FF8" src="https://github.com/user-attachments/assets/56f9a8ce-0f53-4cab-9709-d0d6c6903caf">

**Comment by Username-ghb** [comment] 2024-11-11 12:36
Update: Works now, can't find the reason why but it works now. However i wish that this can be fully prevented in the future since i wouldn't know if it would be unusable for me again

**Comment by TrueZhuangJia** [comment] 2024-11-22 12:24
fixed in latest testflight version

**Closed as completed by TrueZhuangJia** 2024-11-22 12:24 UTC
